#!/bin/sh

SCRIPT_PATH=$(realpath "$0")
SCRIPTS_DIR=$(dirname "$SCRIPT_PATH")
PROJECT_DIR=$(dirname "$SCRIPTS_DIR")

JAR_PATH="$PROJECT_DIR/master/target/scala-2.13/master.jar"

if [ ! -f "$JAR_PATH" ]; then
    echo "Jar not found at $JAR_PATH. Try running 'sbt assembly' first."
    exit 1
fi

java -Xmx8g -jar "$JAR_PATH" "$@"
